version: '3.8'

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    image: auth:1.0.0
    container_name: auth_service
    ports:
      - "8082:8082"
    volumes:
      - shared_data:/app/shared_data

  productlist:
  auth:
    build:
      context: ./productlist
      dockerfile: Dockerfile
    image: productlist:1.0.0
    container_name: productlist_service
    ports:
      - "8081:8081"

  userinfo:
    build:
      context: ./userinfo
      dockerfile: Dockerfile
    image: userinfo:1.0.0
    container_name: userinfo_service
    ports:
      - "8083:8083"
    volumes:
      - shared_data:/app/shared_data

  webserver:
  auth:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    image: webserver:1.0.0
    container_name: webserver_service
    ports:
      - "8080:8080"
volumes:
  shared_data:
  logs: 
