version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: auth
        VERSION: 1.0.1  # Increment the version manually or via script
    image: auth:${VERSION}
    container_name: auth_service
    ports:
      - "8083:8083"

  productlist:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: productlist
        VERSION: 1.0.1
    image: productlist:${VERSION}
    container_name: productlist_service
    ports:
      - "8084:8084"

  userinfo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: userinfo
        VERSION: 1.0.1
    image: userinfo:${VERSION}
    container_name: userinfo_service
    ports:
      - "8085:8085"

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: webserver
        VERSION: 1.0.1
    image: webserver:${VERSION}
    container_name: webserver_service
    ports:
      - "8086:8086"
    depends_on:
      - auth
      - productlist
      - userinfo
